version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3003:3003"
      - "3004:3004"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - "8080:8080"
      - "443:443"