version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3003:3003"
      - "3004:3004"
  client:
    environment:
      - PORT=3002
      - REACT_APP_SOCKET_URL=http://sharpshooters.parseiful.com:3004
      - REACT_APP_PORT=3004
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3002:3002"